- name: catalogue setup
  hosts: catalogue
  become: yes

  tasks:

  - name: setup nodejs
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: ading roboshop
    ansible.builtin.user:
      name: roboshop
      state: present

  - name: creating App folder
    ansible.builtin.file:
     path: /app
     state: directory

  - name: download and unzip roboshop
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /app
      remote_src: yes

  - name: installing npm
    ansible.builtin.shell: npm install 
    args:
     chdir: /app

  - name: copying catalogue.service
    ansible.builtin.copy:
     src: catalogue.service
     dest: /etc/systemd/system/catalogue.service   

  - name: loading daemon-reload
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: enabling and starting service
    ansible.builtin.service:
     name: catalogue
     enabled: yes
     state: started

  - name: copying mongo.repo
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongodb-org-shell
    ansible.builtin.yum:
     name: mongodb-org-shell
     state: installed

  - name: loading schemas
    ansible.builtin.shell: mongo --host 54.85.34.169 </app/schema/catalogue.js                              