- name: redis setup
  hosts: redis
  become: yes

  tasks:
  - name: setup redis
    ansible.builtin.yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm 
      state: installed
      disable_gpg_check: true

  - name: enabling redis module
    ansible.builtin.shell: yum module enable redis:remi-6.2 -y

  - name: installing redis
    ansible.builtin.yum:
      name: redis
      state: installed

  - name: changing IP 127.0.0.1 to 0.0.0.0
    ansible.builtin.replace:  
      path: /etc/redis.conf
      regexp: '127.0.0.1'  
      replace: '0.0.0.0'

  - name: Start & Enable Redis Service
    ansible.builtin.service:
      name: redis 
      enabled: yes
      state: started

